package com.redis.example.demo.vcard;

import java.io.Serializable;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table ext_access_application_function_med
 *
 * @mbg.generated do_not_delete_during_merge Thu Jun 18 14:26:24 CST 2020
 */
public class ExtAccessApplicationFunctionMed implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.id
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   医院机构编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.med_org_code
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private String medOrgCode;

    /**
     * Database Column Remarks:
     *   接口编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.function_code
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private String functionCode;

    /**
     * Database Column Remarks:
     *   是否使用  0 停用  1启用
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.use_status
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private Integer useStatus;

    /**
     * Database Column Remarks:
     *   请求第三方的地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.req_url
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private String reqUrl;

    /**
     * Database Column Remarks:
     *   1 aes 、2 rsa 、3 des
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.encryption_type
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private Integer encryptionType;

    /**
     * Database Column Remarks:
     *   私钥
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.encryption_pri_key
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private String encryptionPriKey;

    /**
     * Database Column Remarks:
     *   公钥
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.encryption_pub_key
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private String encryptionPubKey;

    /**
     * Database Column Remarks:
     *   信息交互加密key
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.encryption_key
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private String encryptionKey;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.gmt_create
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private Date gmtCreate;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.gmt_modified
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private Date gmtModified;

    /**
     * Database Column Remarks:
     *   是否删除0否1是
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column ext_access_application_function_med.is_deleted
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private Boolean isDeleted;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table ext_access_application_function_med
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.id
     *
     * @return the value of ext_access_application_function_med.id
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.id
     *
     * @param id the value for ext_access_application_function_med.id
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.med_org_code
     *
     * @return the value of ext_access_application_function_med.med_org_code
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public String getMedOrgCode() {
        return medOrgCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.med_org_code
     *
     * @param medOrgCode the value for ext_access_application_function_med.med_org_code
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setMedOrgCode(String medOrgCode) {
        this.medOrgCode = medOrgCode == null ? null : medOrgCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.function_code
     *
     * @return the value of ext_access_application_function_med.function_code
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public String getFunctionCode() {
        return functionCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.function_code
     *
     * @param functionCode the value for ext_access_application_function_med.function_code
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setFunctionCode(String functionCode) {
        this.functionCode = functionCode == null ? null : functionCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.use_status
     *
     * @return the value of ext_access_application_function_med.use_status
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public Integer getUseStatus() {
        return useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.use_status
     *
     * @param useStatus the value for ext_access_application_function_med.use_status
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setUseStatus(Integer useStatus) {
        this.useStatus = useStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.req_url
     *
     * @return the value of ext_access_application_function_med.req_url
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public String getReqUrl() {
        return reqUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.req_url
     *
     * @param reqUrl the value for ext_access_application_function_med.req_url
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setReqUrl(String reqUrl) {
        this.reqUrl = reqUrl == null ? null : reqUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.encryption_type
     *
     * @return the value of ext_access_application_function_med.encryption_type
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public Integer getEncryptionType() {
        return encryptionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.encryption_type
     *
     * @param encryptionType the value for ext_access_application_function_med.encryption_type
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setEncryptionType(Integer encryptionType) {
        this.encryptionType = encryptionType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.encryption_pri_key
     *
     * @return the value of ext_access_application_function_med.encryption_pri_key
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public String getEncryptionPriKey() {
        return encryptionPriKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.encryption_pri_key
     *
     * @param encryptionPriKey the value for ext_access_application_function_med.encryption_pri_key
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setEncryptionPriKey(String encryptionPriKey) {
        this.encryptionPriKey = encryptionPriKey == null ? null : encryptionPriKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.encryption_pub_key
     *
     * @return the value of ext_access_application_function_med.encryption_pub_key
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public String getEncryptionPubKey() {
        return encryptionPubKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.encryption_pub_key
     *
     * @param encryptionPubKey the value for ext_access_application_function_med.encryption_pub_key
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setEncryptionPubKey(String encryptionPubKey) {
        this.encryptionPubKey = encryptionPubKey == null ? null : encryptionPubKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.encryption_key
     *
     * @return the value of ext_access_application_function_med.encryption_key
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public String getEncryptionKey() {
        return encryptionKey;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.encryption_key
     *
     * @param encryptionKey the value for ext_access_application_function_med.encryption_key
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setEncryptionKey(String encryptionKey) {
        this.encryptionKey = encryptionKey == null ? null : encryptionKey.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.gmt_create
     *
     * @return the value of ext_access_application_function_med.gmt_create
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.gmt_create
     *
     * @param gmtCreate the value for ext_access_application_function_med.gmt_create
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.gmt_modified
     *
     * @return the value of ext_access_application_function_med.gmt_modified
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public Date getGmtModified() {
        return gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.gmt_modified
     *
     * @param gmtModified the value for ext_access_application_function_med.gmt_modified
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setGmtModified(Date gmtModified) {
        this.gmtModified = gmtModified;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column ext_access_application_function_med.is_deleted
     *
     * @return the value of ext_access_application_function_med.is_deleted
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public Boolean getIsDeleted() {
        return isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column ext_access_application_function_med.is_deleted
     *
     * @param isDeleted the value for ext_access_application_function_med.is_deleted
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    public void setIsDeleted(Boolean isDeleted) {
        this.isDeleted = isDeleted;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ext_access_application_function_med
     *
     * @mbg.generated Thu Jun 18 14:26:24 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", id=").append(id);
        sb.append(", medOrgCode=").append(medOrgCode);
        sb.append(", functionCode=").append(functionCode);
        sb.append(", useStatus=").append(useStatus);
        sb.append(", reqUrl=").append(reqUrl);
        sb.append(", encryptionType=").append(encryptionType);
        sb.append(", encryptionPriKey=").append(encryptionPriKey);
        sb.append(", encryptionPubKey=").append(encryptionPubKey);
        sb.append(", encryptionKey=").append(encryptionKey);
        sb.append(", gmtCreate=").append(gmtCreate);
        sb.append(", gmtModified=").append(gmtModified);
        sb.append(", isDeleted=").append(isDeleted);
        sb.append("]");
        return sb.toString();
    }
}